// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJNmivRC3hwRRs24CzsH_2Mcu4_8a4Gt8',
    appId: '1:75380524958:web:8c2f721e095e9db7aeb88f',
    messagingSenderId: '75380524958',
    projectId: 'shapedetection-30d6c',
    authDomain: 'shapedetection-30d6c.firebaseapp.com',
    storageBucket: 'shapedetection-30d6c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHSgMz1kj4N-_HpYObIOOvou00ZoFmBcI',
    appId: '1:75380524958:android:ff9bdadc6adcd959aeb88f',
    messagingSenderId: '75380524958',
    projectId: 'shapedetection-30d6c',
    storageBucket: 'shapedetection-30d6c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGBU41i3zKXOA1EzAVphlDNrbxgA0FZkE',
    appId: '1:75380524958:ios:73662b5a3016eaefaeb88f',
    messagingSenderId: '75380524958',
    projectId: 'shapedetection-30d6c',
    storageBucket: 'shapedetection-30d6c.appspot.com',
    iosBundleId: 'com.example.shapeDetection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGBU41i3zKXOA1EzAVphlDNrbxgA0FZkE',
    appId: '1:75380524958:ios:73662b5a3016eaefaeb88f',
    messagingSenderId: '75380524958',
    projectId: 'shapedetection-30d6c',
    storageBucket: 'shapedetection-30d6c.appspot.com',
    iosBundleId: 'com.example.shapeDetection',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJNmivRC3hwRRs24CzsH_2Mcu4_8a4Gt8',
    appId: '1:75380524958:web:9f3797c0a53af115aeb88f',
    messagingSenderId: '75380524958',
    projectId: 'shapedetection-30d6c',
    authDomain: 'shapedetection-30d6c.firebaseapp.com',
    storageBucket: 'shapedetection-30d6c.appspot.com',
  );
}
